import { 
  Menu, 
  Clock, 
  Pause, 
  StopCircle, 
  Play, 
  Tag, 
  X,
  Plus,
  Search,
  ChevronRight,
  ChevronLeft,
  Check,
  Edit2,
  Trash2,
  Filter,
  Calendar,
  Target,
  Award,
  TrendingUp,
  TrendingDown,
  BarChart2,
  Home,
  User,
  Bell,
  HelpCircle,
  LogOut,
  Share2,
  Download,
  Upload,
  RefreshCw,
  AlertCircle,
  Info,
  CheckCircle,
  XCircle,
  AlertTriangle,
  Zap,
  Heart,
  Star,
  Bookmark,
  MessageSquare,
  Send,
  Folder,
  Copy,
  Link,
  ExternalLink,
  Globe,
  Map,
  Navigation,
  Compass,
  Activity,
  Volume2,
  VolumeX,
  Mic,
  MicOff,
  Camera,
  Image,
  Film,
  Music,
  Headphones,
  Cloud,
  Lock,
  Unlock,
  Shield,
  Key,
  Eye,
  EyeOff,
  AtSign,
  DollarSign,
  Percent,
  CreditCard,
  Gift,
  MapPin,
  Flag,
  Layers,
  Grid,
  List,
  Sliders,
  Settings,
  Book,
  Wrench,
  Paperclip,
  Anchor,
  Feather,
  Palette,
  Sun,
  Moon,
  CloudRain,
  CloudSnow,
  Wind,
  Thermometer,
  Umbrella,
  Coffee,
  Book,
  BookOpen,
  Save,
  UserPlus,
  UserMinus,
  UserCheck,
  Users,
  Briefcase,
  Building2,
  Lightbulb,
  Flame,
  Sparkles,
  Trophy,
  Medal,
  Crown,
  Gem,
  Coins,
  Wallet,
  Receipt,
  Calculator,
  PieChart,
  LineChart,
  Hash,
} from 'lucide-react-native';
import { iconography } from './tokens';

// Icon mapping for consistent usage across the app
export const Icons = {
  // Navigation & Menu
  menu: Menu,
  close: X,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  home: Home,
  
  // Timer & Controls
  timer: Clock,
  play: Play,
  pause: Pause,
  stop: StopCircle,
  
  // Actions
  add: Plus,
  edit: Edit2,
  delete: Trash2,
  search: Search,
  filter: Filter,
  refresh: RefreshCw,
  share: Share2,
  download: Download,
  upload: Upload,
  save: Save,
  copy: Copy,
  
  // Tags & Categories
  tag: Tag,
  folder: Folder,
  bookmark: Bookmark,
  flag: Flag,
  layers: Layers,
  
  // User & Profile
  user: User,
  users: Users,
  userAdd: UserPlus,
  userRemove: UserMinus,
  userCheck: UserCheck,
  
  // Settings & Tools
  settings: Settings,
  sliders: Sliders,
  tool: Book,
  wrench: Wrench,
  
  // Status & Feedback
  check: Check,
  checkCircle: CheckCircle,
  alert: AlertCircle,
  info: Info,
  warning: AlertTriangle,
  error: XCircle,
  
  // Progress & Achievement
  trophy: Trophy,
  award: Award,
  medal: Medal,
  crown: Crown,
  star: Star,
  gem: Gem,
  target: Target,
  flame: Flame,
  sparkles: Sparkles,
  lightbulb: Lightbulb,
  
  // Energy & Activity
  energy: Zap,
  activity: Activity,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  
  // Charts & Analytics
  barChart: BarChart2,
  pieChart: PieChart,
  lineChart: LineChart,
  
  // Communication
  bell: Bell,
  message: MessageSquare,
  send: Send,
  
  // Media
  camera: Camera,
  image: Image,
  film: Film,
  music: Music,
  headphones: Headphones,
  mic: Mic,
  micOff: MicOff,
  volume: Volume2,
  volumeOff: VolumeX,
  
  // Business & Work
  briefcase: Briefcase,
  building: Building2,
  
  // Nature & Weather
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  rain: CloudRain,
  snow: CloudSnow,
  wind: Wind,
  thermometer: Thermometer,
  umbrella: Umbrella,
  
  // Objects
  book: Book,
  bookOpen: BookOpen,
  coffee: Coffee,
  gift: Gift,
  heart: Heart,
  
  // Finance
  coins: Coins,
  wallet: Wallet,
  creditCard: CreditCard,
  receipt: Receipt,
  calculator: Calculator,
  dollarSign: DollarSign,
  percent: Percent,
  
  // Security
  lock: Lock,
  unlock: Unlock,
  shield: Shield,
  key: Key,
  eye: Eye,
  eyeOff: EyeOff,
  
  // Misc
  help: HelpCircle,
  external: ExternalLink,
  link: Link,
  globe: Globe,
  map: Map,
  mapPin: MapPin,
  navigation: Navigation,
  compass: Compass,
  calendar: Calendar,
  grid: Grid,
  list: List,
  palette: Palette,
  feather: Feather,
  anchor: Anchor,
  paperclip: Paperclip,
  hash: Hash,
  atSign: AtSign,
  logOut: LogOut,
};

// Helper function to get icon with default props
export const getIcon = (name: keyof typeof Icons, customProps?: any) => {
  const Icon = Icons[name];
  return {
    Component: Icon,
    defaultProps: {
      size: iconography.sizes.m,
      color: iconography.colors.default,
      strokeWidth: iconography.strokeWidth,
      ...customProps,
    },
  };
};

// Icon size presets
export const iconSizes = iconography.sizes;

// Icon color presets
export const iconColors = iconography.colors;