export const Colors = {
  background: '#FAFAF7',
  surface: '#FFFFFF',
  textPrimary: '#1A1A18',
  textSecondary: '#6B6B64',
  textTertiary: '#9C9C94',
  accent: '#D4603A',
  accentLight: '#FFF0EB',
  success: '#3A8A5C',
  successLight: '#E8F5ED',
  warning: '#C68B2C',
  warningLight: '#FFF8EC',
  border: '#E8E8E3',
  tabInactive: '#9C9C94',
  tabActive: '#D4603A',
} as const;
