import { Recipe } from '@/types';

export const SEED_RECIPES: Recipe[] = [
  // === BREAKFAST ===
  {
    id: 'b1',
    name: 'Avocado Toast with Poached Eggs',
    description: 'Creamy avocado on toasted sourdough topped with perfectly poached eggs and a sprinkle of red pepper flakes.',
    cuisineType: 'American',
    mealType: 'breakfast',
    dietaryTags: ['omnivore', 'pescatarian'],
    allergens: ['eggs', 'gluten'],
    calories: 420,
    protein: 24,
    carbs: 38,
    fat: 22,
    prepTimeMinutes: 5,
    cookTimeMinutes: 10,
    totalTimeMinutes: 15,
    servings: 2,
    difficulty: 'easy',
    ingredients: [
      { name: 'Sourdough bread', quantity: 2, unit: 'slices', category: 'bakery', isOptional: false },
      { name: 'Ripe avocado', quantity: 1, unit: '', category: 'produce', isOptional: false },
      { name: 'Large eggs', quantity: 2, unit: '', category: 'dairy', isOptional: false },
      { name: 'Olive oil', quantity: 1, unit: 'tbsp', category: 'condiments', isOptional: false },
      { name: 'Salt, pepper, red pepper flakes', quantity: 1, unit: 'pinch', category: 'spices', isOptional: false },
    ],
    instructions: [
      'Toast the sourdough bread until golden and crispy.',
      'Mash the avocado with a fork and season with salt and pepper.',
      'Bring a pot of water to a gentle simmer. Create a vortex and crack eggs in one at a time.',
      'Poach eggs for 3-4 minutes until whites are set but yolks are still runny.',
      'Spread avocado on toast, top with poached eggs, and garnish with red pepper flakes.',
    ],
    imageUrl: null,
    source: 'curated',
  },
  {
    id: 'b2',
    name: 'Greek Yogurt Parfait',
    description: 'Layered Greek yogurt with honey, granola, and fresh mixed berries.',
    cuisineType: 'American',
    mealType: 'breakfast',
    dietaryTags: ['omnivore', 'vegetarian', 'pescatarian'],
    allergens: ['dairy', 'gluten', 'nuts'],
    calories: 380,
    protein: 18,
    carbs: 52,
    fat: 12,
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    totalTimeMinutes: 5,
    servings: 1,
    difficulty: 'easy',
    ingredients: [
      { name: 'Greek yogurt', quantity: 1, unit: 'cup', category: 'dairy', isOptional: false },
      { name: 'Granola', quantity: 0.5, unit: 'cup', category: 'grains', isOptional: false },
      { name: 'Mixed berries', quantity: 0.75, unit: 'cup', category: 'produce', isOptional: false },
      { name: 'Honey', quantity: 1, unit: 'tbsp', category: 'condiments', isOptional: false },
    ],
    instructions: [
      'Layer half the yogurt in a glass or bowl.',
      'Add half the granola and half the berries.',
      'Repeat with remaining yogurt, granola, and berries.',
      'Drizzle with honey and serve immediately.',
    ],
    imageUrl: null,
    source: 'curated',
  },
  {
    id: 'b3',
    name: 'Spinach & Mushroom Omelette',
    description: 'Fluffy three-egg omelette packed with sautéed spinach, mushrooms, and a touch of gruyère.',
    cuisineType: 'French',
    mealType: 'breakfast',
    dietaryTags: ['omnivore', 'vegetarian', 'keto', 'pescatarian', 'gluten-free'],
    allergens: ['eggs', 'dairy'],
    calories: 340,
    protein: 26,
    carbs: 6,
    fat: 24,
    prepTimeMinutes: 5,
    cookTimeMinutes: 7,
    totalTimeMinutes: 12,
    servings: 1,
    difficulty: 'easy',
    ingredients: [
      { name: 'Large eggs', quantity: 3, unit: '', category: 'dairy', isOptional: false },
      { name: 'Fresh spinach', quantity: 1, unit: 'cup', category: 'produce', isOptional: false },
      { name: 'Mushrooms, sliced', quantity: 0.5, unit: 'cup', category: 'produce', isOptional: false },
      { name: 'Gruyère cheese, shredded', quantity: 0.25, unit: 'cup', category: 'dairy', isOptional: false },
      { name: 'Butter', quantity: 1, unit: 'tbsp', category: 'dairy', isOptional: false },
    ],
    instructions: [
      'Whisk eggs with salt and pepper.',
      'Sauté mushrooms in butter until golden, add spinach and cook until wilted. Set aside.',
      'Melt more butter in a non-stick pan over medium heat. Pour in eggs.',
      'When edges start to set, add filling to one half. Fold and cook 1 more minute.',
      'Slide onto a plate and serve.',
    ],
    imageUrl: null,
    source: 'curated',
  },
  {
    id: 'b4',
    name: 'Banana Pancakes',
    description: 'Fluffy banana pancakes made from scratch, served with maple syrup and fresh fruit.',
    cuisineType: 'American',
    mealType: 'breakfast',
    dietaryTags: ['omnivore', 'vegetarian', 'pescatarian'],
    allergens: ['eggs', 'gluten', 'dairy'],
    calories: 450,
    protein: 12,
    carbs: 68,
    fat: 16,
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    totalTimeMinutes: 20,
    servings: 2,
    difficulty: 'medium',
    ingredients: [
      { name: 'Ripe bananas', quantity: 2, unit: '', category: 'produce', isOptional: false },
      { name: 'All-purpose flour', quantity: 1, unit: 'cup', category: 'grains', isOptional: false },
      { name: 'Eggs', quantity: 1, unit: '', category: 'dairy', isOptional: false },
      { name: 'Milk', quantity: 0.75, unit: 'cup', category: 'dairy', isOptional: false },
      { name: 'Maple syrup', quantity: 2, unit: 'tbsp', category: 'condiments', isOptional: false },
      { name: 'Butter for cooking', quantity: 1, unit: 'tbsp', category: 'dairy', isOptional: false },
    ],
    instructions: [
      'Mash bananas in a bowl. Whisk in egg and milk.',
      'Add flour and stir until just combined (lumps are okay).',
      'Heat a griddle or pan with butter over medium heat.',
      'Pour 1/4 cup batter per pancake. Cook until bubbles form, then flip.',
      'Serve with maple syrup and sliced banana.',
    ],
    imageUrl: null,
    source: 'curated',
  },
  {
    id: 'b5',
    name: 'Overnight Oats with Chia Seeds',
    description: 'Creamy no-cook oats with chia seeds, almond milk, and seasonal fruit.',
    cuisineType: 'American',
    mealType: 'breakfast',
    dietaryTags: ['omnivore', 'vegetarian', 'vegan', 'pescatarian'],
    allergens: ['nuts'],
    calories: 350,
    protein: 12,
    carbs: 55,
    fat: 10,
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    totalTimeMinutes: 5,
    servings: 1,
    difficulty: 'easy',
    ingredients: [
      { name: 'Rolled oats', quantity: 0.5, unit: 'cup', category: 'grains', isOptional: false },
      { name: 'Almond milk', quantity: 0.75, unit: 'cup', category: 'dairy', isOptional: false },
      { name: 'Chia seeds', quantity: 1, unit: 'tbsp', category: 'grains', isOptional: false },
      { name: 'Maple syrup', quantity: 1, unit: 'tsp', category: 'condiments', isOptional: false },
      { name: 'Fresh berries', quantity: 0.5, unit: 'cup', category: 'produce', isOptional: false },
    ],
    instructions: [
      'Mix oats, almond milk, chia seeds, and maple syrup in a jar.',
      'Cover and refrigerate overnight (or at least 4 hours).',
      'Top with fresh berries before serving.',
    ],
    imageUrl: null,
    source: 'curated',
  },
  // === LUNCH ===
  {
    id: 'l1',
    name: 'Mediterranean Quinoa Bowl',
    description: 'Protein-packed quinoa bowl with cucumbers, cherry tomatoes, kalamata olives, and lemon-herb dressing.',
    cuisineType: 'Mediterranean',
    mealType: 'lunch',
    dietaryTags: ['omnivore', 'vegetarian', 'vegan', 'pescatarian', 'gluten-free'],
    allergens: [],
    calories: 550,
    protein: 18,
    carbs: 62,
    fat: 24,
    prepTimeMinutes: 15,
    cookTimeMinutes: 10,
    totalTimeMinutes: 25,
    servings: 2,
    difficulty: 'easy',
    ingredients: [
      { name: 'Quinoa', quantity: 1, unit: 'cup', category: 'grains', isOptional: false },
      { name: 'Cucumber', quantity: 1, unit: '', category: 'produce', isOptional: false },
      { name: 'Cherry tomatoes', quantity: 1, unit: 'cup', category: 'produce', isOptional: false },
      { name: 'Kalamata olives', quantity: 0.25, unit: 'cup', category: 'canned', isOptional: false },
      { name: 'Red onion', quantity: 0.25, unit: '', category: 'produce', isOptional: false },
      { name: 'Olive oil', quantity: 2, unit: 'tbsp', category: 'condiments', isOptional: false },
      { name: 'Lemon juice', quantity: 2, unit: 'tbsp', category: 'produce', isOptional: false },
      { name: 'Fresh herbs (basil, cilantro)', quantity: 0.25, unit: 'cup', category: 'produce', isOptional: false },
    ],
    instructions: [
      'Cook quinoa according to package directions. Let cool.',
      'Dice cucumber, halve tomatoes, slice red onion thinly.',
      'Whisk olive oil, lemon juice, salt, and pepper for dressing.',
      'Toss quinoa with vegetables and olives.',
      'Drizzle with dressing and top with fresh herbs.',
    ],
    imageUrl: null,
    source: 'curated',
  },
  {
    id: 'l2',
    name: 'Chicken Caesar Wrap',
    description: 'Grilled chicken breast with crisp romaine, parmesan, and classic Caesar dressing in a whole wheat tortilla.',
    cuisineType: 'American',
    mealType: 'lunch',
    dietaryTags: ['omnivore'],
    allergens: ['gluten', 'dairy', 'eggs'],
    calories: 520,
    protein: 38,
    carbs: 42,
    fat: 22,
    prepTimeMinutes: 10,
    cookTimeMinutes: 12,
    totalTimeMinutes: 22,
    servings: 2,
    difficulty: 'easy',
    ingredients: [
      { name: 'Chicken breast', quantity: 2, unit: 'pieces', category: 'meat', isOptional: false },
      { name: 'Whole wheat tortilla', quantity: 2, unit: '', category: 'bakery', isOptional: false },
      { name: 'Romaine lettuce', quantity: 2, unit: 'cups', category: 'produce', isOptional: false },
      { name: 'Parmesan cheese', quantity: 0.25, unit: 'cup', category: 'dairy', isOptional: false },
      { name: 'Caesar dressing', quantity: 3, unit: 'tbsp', category: 'condiments', isOptional: false },
    ],
    instructions: [
      'Season chicken with salt and pepper. Grill 6 min per side until cooked through.',
      'Slice chicken into strips.',
      'Chop romaine lettuce and toss with Caesar dressing.',
      'Lay tortilla flat. Add dressed lettuce, chicken, and parmesan.',
      'Roll tightly and slice in half diagonally.',
    ],
    imageUrl: null,
    source: 'curated',
  },
  {
    id: 'l3',
    name: 'Thai Basil Chicken Stir-Fry',
    description: 'Quick stir-fry with ground chicken, Thai basil, chili, and garlic served over jasmine rice.',
    cuisineType: 'Thai',
    mealType: 'lunch',
    dietaryTags: ['omnivore', 'gluten-free'],
    allergens: ['soy'],
    calories: 480,
    protein: 32,
    carbs: 48,
    fat: 16,
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    totalTimeMinutes: 20,
    servings: 2,
    difficulty: 'easy',
    ingredients: [
      { name: 'Ground chicken', quantity: 1, unit: 'lb', category: 'meat', isOptional: false },
      { name: 'Fresh Thai basil', quantity: 1, unit: 'cup', category: 'produce', isOptional: false },
      { name: 'Garlic cloves', quantity: 4, unit: '', category: 'produce', isOptional: false },
      { name: 'Thai chili', quantity: 2, unit: '', category: 'produce', isOptional: false },
      { name: 'Soy sauce', quantity: 2, unit: 'tbsp', category: 'condiments', isOptional: false },
      { name: 'Jasmine rice', quantity: 1, unit: 'cup', category: 'grains', isOptional: false },
    ],
    instructions: [
      'Cook jasmine rice according to package directions.',
      'Heat oil in a wok over high heat. Add garlic and chili, stir 30 seconds.',
      'Add ground chicken, breaking it apart. Cook until no longer pink.',
      'Add soy sauce and fish sauce. Toss to combine.',
      'Remove from heat, stir in Thai basil until wilted. Serve over rice.',
    ],
    imageUrl: null,
    source: 'curated',
  },
  {
    id: 'l4',
    name: 'Lentil Soup',
    description: 'Hearty red lentil soup with cumin, turmeric, and a squeeze of lemon.',
    cuisineType: 'Middle Eastern',
    mealType: 'lunch',
    dietaryTags: ['omnivore', 'vegetarian', 'vegan', 'pescatarian', 'gluten-free'],
    allergens: [],
    calories: 380,
    protein: 22,
    carbs: 55,
    fat: 8,
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    totalTimeMinutes: 35,
    servings: 4,
    difficulty: 'easy',
    ingredients: [
      { name: 'Red lentils', quantity: 1.5, unit: 'cups', category: 'grains', isOptional: false },
      { name: 'Onion', quantity: 1, unit: '', category: 'produce', isOptional: false },
      { name: 'Carrots', quantity: 2, unit: '', category: 'produce', isOptional: false },
      { name: 'Garlic cloves', quantity: 3, unit: '', category: 'produce', isOptional: false },
      { name: 'Cumin', quantity: 1, unit: 'tsp', category: 'spices', isOptional: false },
      { name: 'Turmeric', quantity: 0.5, unit: 'tsp', category: 'spices', isOptional: false },
      { name: 'Vegetable broth', quantity: 4, unit: 'cups', category: 'canned', isOptional: false },
      { name: 'Lemon', quantity: 1, unit: '', category: 'produce', isOptional: false },
    ],
    instructions: [
      'Dice onion, carrots, and mince garlic.',
      'Sauté onion in olive oil until soft. Add garlic, cumin, and turmeric.',
      'Add lentils, carrots, and broth. Bring to a boil.',
      'Reduce heat and simmer 20-25 minutes until lentils are tender.',
      'Blend partially for a creamy texture. Finish with lemon juice.',
    ],
    imageUrl: null,
    source: 'curated',
  },
  {
    id: 'l5',
    name: 'Caprese Salad with Burrata',
    description: 'Fresh heirloom tomatoes, creamy burrata, basil, and balsamic reduction.',
    cuisineType: 'Italian',
    mealType: 'lunch',
    dietaryTags: ['omnivore', 'vegetarian', 'pescatarian', 'gluten-free', 'keto'],
    allergens: ['dairy'],
    calories: 420,
    protein: 20,
    carbs: 12,
    fat: 34,
    prepTimeMinutes: 10,
    cookTimeMinutes: 0,
    totalTimeMinutes: 10,
    servings: 2,
    difficulty: 'easy',
    ingredients: [
      { name: 'Heirloom tomatoes', quantity: 3, unit: '', category: 'produce', isOptional: false },
      { name: 'Burrata cheese', quantity: 1, unit: 'ball', category: 'dairy', isOptional: false },
      { name: 'Fresh basil', quantity: 8, unit: 'leaves', category: 'produce', isOptional: false },
      { name: 'Extra-virgin olive oil', quantity: 2, unit: 'tbsp', category: 'condiments', isOptional: false },
      { name: 'Balsamic reduction', quantity: 1, unit: 'tbsp', category: 'condiments', isOptional: false },
    ],
    instructions: [
      'Slice tomatoes into thick rounds and arrange on a platter.',
      'Tear burrata over the tomatoes.',
      'Scatter basil leaves.',
      'Drizzle with olive oil and balsamic reduction.',
      'Season with flaky salt and cracked pepper.',
    ],
    imageUrl: null,
    source: 'curated',
  },
  // === DINNER ===
  {
    id: 'd1',
    name: 'Herb-Crusted Salmon with Roasted Vegetables',
    description: 'Oven-baked salmon with a herb and breadcrumb crust alongside roasted seasonal vegetables.',
    cuisineType: 'American',
    mealType: 'dinner',
    dietaryTags: ['omnivore', 'pescatarian'],
    allergens: ['fish', 'gluten'],
    calories: 620,
    protein: 42,
    carbs: 32,
    fat: 36,
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    totalTimeMinutes: 35,
    servings: 2,
    difficulty: 'medium',
    ingredients: [
      { name: 'Salmon fillets', quantity: 2, unit: 'pieces', category: 'seafood', isOptional: false },
      { name: 'Mixed salad greens', quantity: 1, unit: 'bag', category: 'produce', isOptional: false },
      { name: 'Zucchini', quantity: 1, unit: '', category: 'produce', isOptional: false },
      { name: 'Bell pepper', quantity: 1, unit: '', category: 'produce', isOptional: false },
      { name: 'Breadcrumbs', quantity: 0.25, unit: 'cup', category: 'bakery', isOptional: false },
      { name: 'Fresh dill', quantity: 2, unit: 'tbsp', category: 'produce', isOptional: false },
      { name: 'Olive oil', quantity: 2, unit: 'tbsp', category: 'condiments', isOptional: false },
      { name: 'Lemon', quantity: 1, unit: '', category: 'produce', isOptional: false },
    ],
    instructions: [
      'Preheat oven to 400°F (200°C).',
      'Toss chopped vegetables with olive oil, salt, and pepper. Spread on a baking sheet.',
      'Mix breadcrumbs with dill, lemon zest, and olive oil.',
      'Place salmon on top of vegetables. Press herb crust onto salmon.',
      'Bake 18-20 minutes until salmon flakes easily.',
      'Serve with a squeeze of fresh lemon.',
    ],
    imageUrl: null,
    source: 'curated',
  },
  {
    id: 'd2',
    name: 'Chicken Tikka Masala',
    description: 'Tender chicken in a rich, spiced tomato cream sauce served with basmati rice and naan.',
    cuisineType: 'Indian',
    mealType: 'dinner',
    dietaryTags: ['omnivore'],
    allergens: ['dairy'],
    calories: 680,
    protein: 40,
    carbs: 58,
    fat: 28,
    prepTimeMinutes: 20,
    cookTimeMinutes: 30,
    totalTimeMinutes: 50,
    servings: 4,
    difficulty: 'medium',
    ingredients: [
      { name: 'Chicken thighs, boneless', quantity: 1.5, unit: 'lbs', category: 'meat', isOptional: false },
      { name: 'Yogurt', quantity: 0.5, unit: 'cup', category: 'dairy', isOptional: false },
      { name: 'Crushed tomatoes', quantity: 1, unit: 'can', category: 'canned', isOptional: false },
      { name: 'Heavy cream', quantity: 0.5, unit: 'cup', category: 'dairy', isOptional: false },
      { name: 'Garam masala', quantity: 2, unit: 'tsp', category: 'spices', isOptional: false },
      { name: 'Basmati rice', quantity: 1.5, unit: 'cups', category: 'grains', isOptional: false },
      { name: 'Onion', quantity: 1, unit: '', category: 'produce', isOptional: false },
      { name: 'Garlic cloves', quantity: 4, unit: '', category: 'produce', isOptional: false },
      { name: 'Fresh ginger', quantity: 1, unit: 'tbsp', category: 'produce', isOptional: false },
    ],
    instructions: [
      'Marinate chicken in yogurt and spices for at least 30 minutes.',
      'Cook rice according to package directions.',
      'Sauté onion, garlic, and ginger. Add spices and cook 1 minute.',
      'Add chicken and cook until browned.',
      'Pour in crushed tomatoes, simmer 15 minutes.',
      'Stir in cream and cook 5 more minutes. Serve over rice.',
    ],
    imageUrl: null,
    source: 'curated',
  },
  {
    id: 'd3',
    name: 'Vegetable Pad Thai',
    description: 'Rice noodles with tofu, bean sprouts, peanuts, and tangy tamarind sauce.',
    cuisineType: 'Thai',
    mealType: 'dinner',
    dietaryTags: ['omnivore', 'vegetarian', 'vegan', 'pescatarian'],
    allergens: ['nuts', 'soy'],
    calories: 520,
    protein: 18,
    carbs: 68,
    fat: 20,
    prepTimeMinutes: 15,
    cookTimeMinutes: 10,
    totalTimeMinutes: 25,
    servings: 2,
    difficulty: 'medium',
    ingredients: [
      { name: 'Rice noodles', quantity: 8, unit: 'oz', category: 'grains', isOptional: false },
      { name: 'Firm tofu, cubed', quantity: 8, unit: 'oz', category: 'produce', isOptional: false },
      { name: 'Bean sprouts', quantity: 1, unit: 'cup', category: 'produce', isOptional: false },
      { name: 'Peanuts, crushed', quantity: 0.25, unit: 'cup', category: 'other', isOptional: false },
      { name: 'Tamarind paste', quantity: 2, unit: 'tbsp', category: 'condiments', isOptional: false },
      { name: 'Lime', quantity: 1, unit: '', category: 'produce', isOptional: false },
      { name: 'Green onions', quantity: 3, unit: '', category: 'produce', isOptional: false },
    ],
    instructions: [
      'Soak rice noodles in hot water until pliable. Drain.',
      'Press and cube tofu. Pan-fry until golden on all sides.',
      'Mix tamarind paste, soy sauce, sugar, and lime juice for the sauce.',
      'Stir-fry noodles with sauce until coated. Add tofu and bean sprouts.',
      'Top with crushed peanuts, green onions, and lime wedges.',
    ],
    imageUrl: null,
    source: 'curated',
  },
  {
    id: 'd4',
    name: 'Grilled Steak with Sweet Potato Mash',
    description: 'Perfectly seared ribeye with creamy garlic sweet potato mash and steamed broccolini.',
    cuisineType: 'American',
    mealType: 'dinner',
    dietaryTags: ['omnivore', 'gluten-free'],
    allergens: ['dairy'],
    calories: 720,
    protein: 48,
    carbs: 42,
    fat: 38,
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    totalTimeMinutes: 35,
    servings: 2,
    difficulty: 'medium',
    ingredients: [
      { name: 'Ribeye steak', quantity: 2, unit: 'pieces', category: 'meat', isOptional: false },
      { name: 'Sweet potatoes', quantity: 2, unit: 'large', category: 'produce', isOptional: false },
      { name: 'Butter', quantity: 2, unit: 'tbsp', category: 'dairy', isOptional: false },
      { name: 'Garlic cloves', quantity: 2, unit: '', category: 'produce', isOptional: false },
      { name: 'Broccolini', quantity: 1, unit: 'bunch', category: 'produce', isOptional: false },
    ],
    instructions: [
      'Peel and boil sweet potatoes until tender. Mash with butter and garlic.',
      'Season steaks with salt and pepper. Let rest at room temperature 20 minutes.',
      'Heat a cast iron skillet to high. Sear steaks 3-4 min per side for medium-rare.',
      'Rest steak 5 minutes before slicing.',
      'Steam broccolini for 3-4 minutes. Serve alongside steak and mash.',
    ],
    imageUrl: null,
    source: 'curated',
  },
  {
    id: 'd5',
    name: 'Mushroom Risotto',
    description: 'Creamy Arborio rice with mixed mushrooms, white wine, and aged parmesan.',
    cuisineType: 'Italian',
    mealType: 'dinner',
    dietaryTags: ['omnivore', 'vegetarian', 'pescatarian'],
    allergens: ['dairy'],
    calories: 580,
    protein: 16,
    carbs: 72,
    fat: 24,
    prepTimeMinutes: 10,
    cookTimeMinutes: 30,
    totalTimeMinutes: 40,
    servings: 4,
    difficulty: 'medium',
    ingredients: [
      { name: 'Arborio rice', quantity: 1.5, unit: 'cups', category: 'grains', isOptional: false },
      { name: 'Mixed mushrooms', quantity: 12, unit: 'oz', category: 'produce', isOptional: false },
      { name: 'White wine', quantity: 0.5, unit: 'cup', category: 'other', isOptional: false },
      { name: 'Vegetable broth', quantity: 4, unit: 'cups', category: 'canned', isOptional: false },
      { name: 'Parmesan cheese', quantity: 0.5, unit: 'cup', category: 'dairy', isOptional: false },
      { name: 'Butter', quantity: 2, unit: 'tbsp', category: 'dairy', isOptional: false },
      { name: 'Shallot', quantity: 1, unit: '', category: 'produce', isOptional: false },
    ],
    instructions: [
      'Warm broth in a saucepan. Keep at a gentle simmer.',
      'Sauté mushrooms in butter until golden. Set aside.',
      'Sauté shallot, add rice and toast 2 minutes. Deglaze with wine.',
      'Add broth one ladle at a time, stirring until absorbed before adding more.',
      'When rice is al dente, fold in mushrooms, parmesan, and butter.',
      'Season and serve immediately.',
    ],
    imageUrl: null,
    source: 'curated',
  },
  // === MORE BREAKFAST ===
  {
    id: 'b6',
    name: 'Shakshuka',
    description: 'Eggs poached in a spiced tomato and pepper sauce, served with crusty bread.',
    cuisineType: 'Middle Eastern',
    mealType: 'breakfast',
    dietaryTags: ['omnivore', 'vegetarian', 'pescatarian', 'gluten-free'],
    allergens: ['eggs'],
    calories: 360,
    protein: 20,
    carbs: 28,
    fat: 18,
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    totalTimeMinutes: 30,
    servings: 2,
    difficulty: 'easy',
    ingredients: [
      { name: 'Large eggs', quantity: 4, unit: '', category: 'dairy', isOptional: false },
      { name: 'Crushed tomatoes', quantity: 1, unit: 'can', category: 'canned', isOptional: false },
      { name: 'Red bell pepper', quantity: 1, unit: '', category: 'produce', isOptional: false },
      { name: 'Onion', quantity: 1, unit: '', category: 'produce', isOptional: false },
      { name: 'Cumin', quantity: 1, unit: 'tsp', category: 'spices', isOptional: false },
      { name: 'Paprika', quantity: 1, unit: 'tsp', category: 'spices', isOptional: false },
    ],
    instructions: [
      'Sauté diced onion and bell pepper until soft.',
      'Add cumin and paprika, cook 1 minute.',
      'Pour in crushed tomatoes, simmer 10 minutes.',
      'Make 4 wells in the sauce. Crack an egg into each.',
      'Cover and cook 5-7 minutes until whites are set.',
    ],
    imageUrl: null,
    source: 'curated',
  },
  {
    id: 'b7',
    name: 'Açaí Bowl',
    description: 'Thick açaí smoothie bowl topped with granola, banana, and coconut flakes.',
    cuisineType: 'Brazilian',
    mealType: 'breakfast',
    dietaryTags: ['omnivore', 'vegetarian', 'vegan', 'pescatarian', 'gluten-free'],
    allergens: ['nuts'],
    calories: 400,
    protein: 8,
    carbs: 64,
    fat: 14,
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    totalTimeMinutes: 5,
    servings: 1,
    difficulty: 'easy',
    ingredients: [
      { name: 'Açaí puree (frozen)', quantity: 2, unit: 'packs', category: 'frozen', isOptional: false },
      { name: 'Banana', quantity: 1, unit: '', category: 'produce', isOptional: false },
      { name: 'Almond milk', quantity: 0.5, unit: 'cup', category: 'dairy', isOptional: false },
      { name: 'Granola', quantity: 0.25, unit: 'cup', category: 'grains', isOptional: false },
      { name: 'Coconut flakes', quantity: 1, unit: 'tbsp', category: 'other', isOptional: false },
    ],
    instructions: [
      'Blend açaí puree, half the banana, and almond milk until thick.',
      'Pour into a bowl.',
      'Top with sliced banana, granola, and coconut flakes.',
    ],
    imageUrl: null,
    source: 'curated',
  },
  {
    id: 'b8',
    name: 'Smoked Salmon Bagel',
    description: 'Toasted everything bagel with cream cheese, smoked salmon, capers, and red onion.',
    cuisineType: 'American',
    mealType: 'breakfast',
    dietaryTags: ['omnivore', 'pescatarian'],
    allergens: ['gluten', 'dairy', 'fish'],
    calories: 460,
    protein: 28,
    carbs: 42,
    fat: 20,
    prepTimeMinutes: 5,
    cookTimeMinutes: 3,
    totalTimeMinutes: 8,
    servings: 1,
    difficulty: 'easy',
    ingredients: [
      { name: 'Everything bagel', quantity: 1, unit: '', category: 'bakery', isOptional: false },
      { name: 'Cream cheese', quantity: 2, unit: 'tbsp', category: 'dairy', isOptional: false },
      { name: 'Smoked salmon', quantity: 3, unit: 'oz', category: 'seafood', isOptional: false },
      { name: 'Capers', quantity: 1, unit: 'tbsp', category: 'condiments', isOptional: false },
      { name: 'Red onion, thinly sliced', quantity: 2, unit: 'rings', category: 'produce', isOptional: false },
    ],
    instructions: [
      'Toast the bagel until golden.',
      'Spread cream cheese on both halves.',
      'Layer smoked salmon on bottom half.',
      'Top with capers, red onion, and a squeeze of lemon.',
    ],
    imageUrl: null,
    source: 'curated',
  },
  {
    id: 'b9',
    name: 'Tofu Scramble',
    description: 'Seasoned crumbled tofu with peppers, onions, and nutritional yeast — a plant-based egg scramble.',
    cuisineType: 'American',
    mealType: 'breakfast',
    dietaryTags: ['omnivore', 'vegetarian', 'vegan', 'pescatarian', 'gluten-free'],
    allergens: ['soy'],
    calories: 290,
    protein: 22,
    carbs: 14,
    fat: 18,
    prepTimeMinutes: 5,
    cookTimeMinutes: 10,
    totalTimeMinutes: 15,
    servings: 2,
    difficulty: 'easy',
    ingredients: [
      { name: 'Firm tofu', quantity: 14, unit: 'oz', category: 'produce', isOptional: false },
      { name: 'Bell pepper, diced', quantity: 1, unit: '', category: 'produce', isOptional: false },
      { name: 'Onion, diced', quantity: 0.5, unit: '', category: 'produce', isOptional: false },
      { name: 'Nutritional yeast', quantity: 2, unit: 'tbsp', category: 'spices', isOptional: false },
      { name: 'Turmeric', quantity: 0.5, unit: 'tsp', category: 'spices', isOptional: false },
    ],
    instructions: [
      'Press tofu and crumble into pieces.',
      'Sauté onion and pepper until soft.',
      'Add crumbled tofu, turmeric, and nutritional yeast.',
      'Cook 5-7 minutes, stirring occasionally.',
      'Season with salt and pepper. Serve warm.',
    ],
    imageUrl: null,
    source: 'curated',
  },
  {
    id: 'b10',
    name: 'French Toast with Berries',
    description: 'Thick-cut brioche dipped in vanilla custard, pan-fried golden, topped with fresh berries.',
    cuisineType: 'French',
    mealType: 'breakfast',
    dietaryTags: ['omnivore', 'vegetarian', 'pescatarian'],
    allergens: ['eggs', 'gluten', 'dairy'],
    calories: 480,
    protein: 14,
    carbs: 58,
    fat: 22,
    prepTimeMinutes: 5,
    cookTimeMinutes: 10,
    totalTimeMinutes: 15,
    servings: 2,
    difficulty: 'easy',
    ingredients: [
      { name: 'Brioche bread', quantity: 4, unit: 'slices', category: 'bakery', isOptional: false },
      { name: 'Eggs', quantity: 2, unit: '', category: 'dairy', isOptional: false },
      { name: 'Milk', quantity: 0.5, unit: 'cup', category: 'dairy', isOptional: false },
      { name: 'Vanilla extract', quantity: 1, unit: 'tsp', category: 'spices', isOptional: false },
      { name: 'Mixed berries', quantity: 1, unit: 'cup', category: 'produce', isOptional: false },
      { name: 'Maple syrup', quantity: 2, unit: 'tbsp', category: 'condiments', isOptional: false },
    ],
    instructions: [
      'Whisk eggs, milk, and vanilla in a shallow dish.',
      'Dip each bread slice, coating both sides.',
      'Cook in buttered pan 2-3 min per side until golden.',
      'Top with fresh berries and maple syrup.',
    ],
    imageUrl: null,
    source: 'curated',
  },
  // === MORE LUNCH ===
  {
    id: 'l6',
    name: 'Black Bean Tacos',
    description: 'Crispy corn tortillas with seasoned black beans, avocado, pickled onion, and lime crema.',
    cuisineType: 'Mexican',
    mealType: 'lunch',
    dietaryTags: ['omnivore', 'vegetarian', 'vegan', 'pescatarian', 'gluten-free'],
    allergens: [],
    calories: 440,
    protein: 16,
    carbs: 56,
    fat: 18,
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    totalTimeMinutes: 20,
    servings: 2,
    difficulty: 'easy',
    ingredients: [
      { name: 'Black beans', quantity: 1, unit: 'can', category: 'canned', isOptional: false },
      { name: 'Corn tortillas', quantity: 6, unit: '', category: 'bakery', isOptional: false },
      { name: 'Avocado', quantity: 1, unit: '', category: 'produce', isOptional: false },
      { name: 'Red onion, pickled', quantity: 0.25, unit: 'cup', category: 'produce', isOptional: false },
      { name: 'Lime', quantity: 1, unit: '', category: 'produce', isOptional: false },
      { name: 'Cumin', quantity: 1, unit: 'tsp', category: 'spices', isOptional: false },
    ],
    instructions: [
      'Drain and rinse black beans. Heat with cumin and salt.',
      'Warm tortillas in a dry skillet.',
      'Fill with beans, sliced avocado, and pickled onion.',
      'Squeeze lime over top and serve.',
    ],
    imageUrl: null,
    source: 'curated',
  },
  {
    id: 'l7',
    name: 'Japanese Miso Ramen',
    description: 'Rich miso broth with ramen noodles, soft-boiled egg, corn, and green onions.',
    cuisineType: 'Japanese',
    mealType: 'lunch',
    dietaryTags: ['omnivore', 'pescatarian'],
    allergens: ['soy', 'gluten', 'eggs'],
    calories: 520,
    protein: 24,
    carbs: 62,
    fat: 20,
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    totalTimeMinutes: 25,
    servings: 2,
    difficulty: 'medium',
    ingredients: [
      { name: 'Ramen noodles', quantity: 2, unit: 'portions', category: 'grains', isOptional: false },
      { name: 'White miso paste', quantity: 3, unit: 'tbsp', category: 'condiments', isOptional: false },
      { name: 'Vegetable broth', quantity: 4, unit: 'cups', category: 'canned', isOptional: false },
      { name: 'Eggs', quantity: 2, unit: '', category: 'dairy', isOptional: false },
      { name: 'Corn kernels', quantity: 0.5, unit: 'cup', category: 'frozen', isOptional: false },
      { name: 'Green onions', quantity: 3, unit: '', category: 'produce', isOptional: false },
    ],
    instructions: [
      'Soft-boil eggs (6.5 min), peel and halve.',
      'Heat broth and whisk in miso paste (don\'t boil after adding miso).',
      'Cook ramen noodles according to package.',
      'Divide noodles into bowls, ladle broth over.',
      'Top with egg halves, corn, and sliced green onions.',
    ],
    imageUrl: null,
    source: 'curated',
  },
  {
    id: 'l8',
    name: 'Grilled Chicken Salad',
    description: 'Mixed greens with grilled chicken, cherry tomatoes, avocado, and lemon vinaigrette.',
    cuisineType: 'American',
    mealType: 'lunch',
    dietaryTags: ['omnivore', 'gluten-free'],
    allergens: [],
    calories: 420,
    protein: 36,
    carbs: 18,
    fat: 24,
    prepTimeMinutes: 10,
    cookTimeMinutes: 12,
    totalTimeMinutes: 22,
    servings: 2,
    difficulty: 'easy',
    ingredients: [
      { name: 'Chicken breast', quantity: 2, unit: 'pieces', category: 'meat', isOptional: false },
      { name: 'Mixed salad greens', quantity: 4, unit: 'cups', category: 'produce', isOptional: false },
      { name: 'Cherry tomatoes', quantity: 1, unit: 'cup', category: 'produce', isOptional: false },
      { name: 'Avocado', quantity: 1, unit: '', category: 'produce', isOptional: false },
      { name: 'Olive oil', quantity: 2, unit: 'tbsp', category: 'condiments', isOptional: false },
      { name: 'Lemon', quantity: 1, unit: '', category: 'produce', isOptional: false },
    ],
    instructions: [
      'Season chicken and grill 6 min per side.',
      'Let rest 5 minutes, then slice.',
      'Toss greens with halved tomatoes and sliced avocado.',
      'Whisk olive oil with lemon juice for dressing.',
      'Top salad with chicken and drizzle dressing.',
    ],
    imageUrl: null,
    source: 'curated',
  },
  {
    id: 'l9',
    name: 'Falafel Pita Bowl',
    description: 'Crispy baked falafel with hummus, cucumber, tomato, and tahini drizzle.',
    cuisineType: 'Middle Eastern',
    mealType: 'lunch',
    dietaryTags: ['omnivore', 'vegetarian', 'vegan', 'pescatarian'],
    allergens: ['sesame', 'gluten'],
    calories: 510,
    protein: 20,
    carbs: 58,
    fat: 22,
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    totalTimeMinutes: 35,
    servings: 2,
    difficulty: 'medium',
    ingredients: [
      { name: 'Chickpeas', quantity: 1, unit: 'can', category: 'canned', isOptional: false },
      { name: 'Fresh parsley', quantity: 0.5, unit: 'cup', category: 'produce', isOptional: false },
      { name: 'Pita bread', quantity: 2, unit: '', category: 'bakery', isOptional: false },
      { name: 'Hummus', quantity: 0.5, unit: 'cup', category: 'condiments', isOptional: false },
      { name: 'Cucumber', quantity: 1, unit: '', category: 'produce', isOptional: false },
      { name: 'Tahini', quantity: 2, unit: 'tbsp', category: 'condiments', isOptional: false },
    ],
    instructions: [
      'Blend chickpeas, parsley, garlic, cumin, and salt.',
      'Form into small patties. Bake at 375°F for 20 min, flipping halfway.',
      'Warm pita and spread with hummus.',
      'Add falafel, diced cucumber, and tomato.',
      'Drizzle with tahini thinned with lemon juice.',
    ],
    imageUrl: null,
    source: 'curated',
  },
  {
    id: 'l10',
    name: 'Tuna Niçoise Salad',
    description: 'Classic French composed salad with seared tuna, green beans, olives, and eggs.',
    cuisineType: 'French',
    mealType: 'lunch',
    dietaryTags: ['omnivore', 'pescatarian', 'gluten-free'],
    allergens: ['fish', 'eggs'],
    calories: 480,
    protein: 38,
    carbs: 22,
    fat: 28,
    prepTimeMinutes: 15,
    cookTimeMinutes: 10,
    totalTimeMinutes: 25,
    servings: 2,
    difficulty: 'medium',
    ingredients: [
      { name: 'Tuna steaks', quantity: 2, unit: 'pieces', category: 'seafood', isOptional: false },
      { name: 'Green beans', quantity: 1, unit: 'cup', category: 'produce', isOptional: false },
      { name: 'Hard-boiled eggs', quantity: 2, unit: '', category: 'dairy', isOptional: false },
      { name: 'Niçoise olives', quantity: 0.25, unit: 'cup', category: 'canned', isOptional: false },
      { name: 'Small potatoes', quantity: 4, unit: '', category: 'produce', isOptional: false },
      { name: 'Dijon vinaigrette', quantity: 3, unit: 'tbsp', category: 'condiments', isOptional: false },
    ],
    instructions: [
      'Boil potatoes until tender. Blanch green beans.',
      'Sear tuna 2 min per side for rare.',
      'Arrange greens, potatoes, beans, olives, and halved eggs on plates.',
      'Slice tuna and place on top.',
      'Drizzle with Dijon vinaigrette.',
    ],
    imageUrl: null,
    source: 'curated',
  },
  // === MORE DINNER ===
  {
    id: 'd6',
    name: 'Lemon Garlic Shrimp Pasta',
    description: 'Linguine with sautéed shrimp in a bright lemon garlic butter sauce with fresh parsley.',
    cuisineType: 'Italian',
    mealType: 'dinner',
    dietaryTags: ['omnivore', 'pescatarian'],
    allergens: ['shellfish', 'gluten', 'dairy'],
    calories: 580,
    protein: 34,
    carbs: 62,
    fat: 22,
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    totalTimeMinutes: 25,
    servings: 2,
    difficulty: 'easy',
    ingredients: [
      { name: 'Linguine', quantity: 8, unit: 'oz', category: 'grains', isOptional: false },
      { name: 'Large shrimp, peeled', quantity: 1, unit: 'lb', category: 'seafood', isOptional: false },
      { name: 'Garlic cloves', quantity: 4, unit: '', category: 'produce', isOptional: false },
      { name: 'Butter', quantity: 2, unit: 'tbsp', category: 'dairy', isOptional: false },
      { name: 'Lemon', quantity: 1, unit: '', category: 'produce', isOptional: false },
      { name: 'Fresh parsley', quantity: 0.25, unit: 'cup', category: 'produce', isOptional: false },
    ],
    instructions: [
      'Cook linguine to al dente. Reserve 1/2 cup pasta water.',
      'Sauté garlic in butter 30 seconds. Add shrimp, cook 2-3 min per side.',
      'Add lemon juice and zest, toss with pasta.',
      'Add pasta water as needed for sauciness.',
      'Garnish with chopped parsley.',
    ],
    imageUrl: null,
    source: 'curated',
  },
  {
    id: 'd7',
    name: 'Korean Bibimbap',
    description: 'Rice bowl topped with seasoned vegetables, gochujang, a fried egg, and sesame oil.',
    cuisineType: 'Korean',
    mealType: 'dinner',
    dietaryTags: ['omnivore', 'vegetarian', 'pescatarian'],
    allergens: ['eggs', 'soy', 'sesame'],
    calories: 540,
    protein: 22,
    carbs: 72,
    fat: 18,
    prepTimeMinutes: 20,
    cookTimeMinutes: 15,
    totalTimeMinutes: 35,
    servings: 2,
    difficulty: 'medium',
    ingredients: [
      { name: 'Short-grain rice', quantity: 1.5, unit: 'cups', category: 'grains', isOptional: false },
      { name: 'Spinach', quantity: 2, unit: 'cups', category: 'produce', isOptional: false },
      { name: 'Carrots, julienned', quantity: 1, unit: '', category: 'produce', isOptional: false },
      { name: 'Zucchini, sliced', quantity: 1, unit: '', category: 'produce', isOptional: false },
      { name: 'Eggs', quantity: 2, unit: '', category: 'dairy', isOptional: false },
      { name: 'Gochujang', quantity: 2, unit: 'tbsp', category: 'condiments', isOptional: false },
      { name: 'Sesame oil', quantity: 1, unit: 'tbsp', category: 'condiments', isOptional: false },
    ],
    instructions: [
      'Cook rice according to package.',
      'Blanch spinach, sauté carrots and zucchini separately with sesame oil.',
      'Fry eggs sunny side up.',
      'Arrange rice in bowls, top with vegetables in sections.',
      'Place egg on top. Serve with gochujang on the side.',
    ],
    imageUrl: null,
    source: 'curated',
  },
  {
    id: 'd8',
    name: 'Stuffed Bell Peppers',
    description: 'Roasted bell peppers filled with seasoned ground turkey, rice, and melted cheese.',
    cuisineType: 'American',
    mealType: 'dinner',
    dietaryTags: ['omnivore', 'gluten-free'],
    allergens: ['dairy'],
    calories: 480,
    protein: 32,
    carbs: 38,
    fat: 22,
    prepTimeMinutes: 15,
    cookTimeMinutes: 30,
    totalTimeMinutes: 45,
    servings: 4,
    difficulty: 'medium',
    ingredients: [
      { name: 'Bell peppers', quantity: 4, unit: 'large', category: 'produce', isOptional: false },
      { name: 'Ground turkey', quantity: 1, unit: 'lb', category: 'meat', isOptional: false },
      { name: 'Cooked rice', quantity: 1, unit: 'cup', category: 'grains', isOptional: false },
      { name: 'Crushed tomatoes', quantity: 0.5, unit: 'cup', category: 'canned', isOptional: false },
      { name: 'Shredded cheese', quantity: 0.5, unit: 'cup', category: 'dairy', isOptional: false },
    ],
    instructions: [
      'Preheat oven to 375°F. Cut tops off peppers and remove seeds.',
      'Brown turkey with onion and garlic. Season with salt, pepper, oregano.',
      'Mix turkey with rice and crushed tomatoes.',
      'Stuff peppers, top with cheese, place in baking dish.',
      'Bake 25-30 minutes until peppers are tender and cheese is melted.',
    ],
    imageUrl: null,
    source: 'curated',
  },
  {
    id: 'd9',
    name: 'Coconut Curry with Chickpeas',
    description: 'Creamy coconut milk curry with chickpeas, sweet potato, and fresh cilantro over rice.',
    cuisineType: 'Indian',
    mealType: 'dinner',
    dietaryTags: ['omnivore', 'vegetarian', 'vegan', 'pescatarian', 'gluten-free'],
    allergens: [],
    calories: 520,
    protein: 16,
    carbs: 68,
    fat: 22,
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    totalTimeMinutes: 35,
    servings: 4,
    difficulty: 'easy',
    ingredients: [
      { name: 'Chickpeas', quantity: 1, unit: 'can', category: 'canned', isOptional: false },
      { name: 'Coconut milk', quantity: 1, unit: 'can', category: 'canned', isOptional: false },
      { name: 'Sweet potato, cubed', quantity: 1, unit: 'large', category: 'produce', isOptional: false },
      { name: 'Curry powder', quantity: 2, unit: 'tbsp', category: 'spices', isOptional: false },
      { name: 'Basmati rice', quantity: 1.5, unit: 'cups', category: 'grains', isOptional: false },
      { name: 'Fresh cilantro', quantity: 0.25, unit: 'cup', category: 'produce', isOptional: false },
    ],
    instructions: [
      'Cook rice according to package.',
      'Sauté onion, add curry powder, cook 1 minute.',
      'Add cubed sweet potato and coconut milk. Simmer 15 min.',
      'Add chickpeas, cook 5 more minutes until sweet potato is tender.',
      'Serve over rice, garnish with cilantro.',
    ],
    imageUrl: null,
    source: 'curated',
  },
  {
    id: 'd10',
    name: 'Pan-Seared Duck Breast',
    description: 'Crispy-skinned duck breast with cherry reduction, served with roasted fingerling potatoes.',
    cuisineType: 'French',
    mealType: 'dinner',
    dietaryTags: ['omnivore', 'gluten-free'],
    allergens: [],
    calories: 650,
    protein: 36,
    carbs: 34,
    fat: 40,
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    totalTimeMinutes: 35,
    servings: 2,
    difficulty: 'hard',
    ingredients: [
      { name: 'Duck breasts', quantity: 2, unit: '', category: 'meat', isOptional: false },
      { name: 'Fresh cherries or cherry preserves', quantity: 0.5, unit: 'cup', category: 'produce', isOptional: false },
      { name: 'Fingerling potatoes', quantity: 1, unit: 'lb', category: 'produce', isOptional: false },
      { name: 'Red wine', quantity: 0.25, unit: 'cup', category: 'other', isOptional: false },
      { name: 'Fresh thyme', quantity: 3, unit: 'sprigs', category: 'produce', isOptional: false },
    ],
    instructions: [
      'Score duck skin in a crosshatch. Season with salt.',
      'Place skin-down in cold pan. Cook on medium 12-15 min to render fat.',
      'Flip and cook 3-4 min more. Rest 5 minutes.',
      'Roast halved potatoes at 425°F with duck fat, thyme, 20 min.',
      'Simmer cherries with red wine until reduced. Spoon over sliced duck.',
    ],
    imageUrl: null,
    source: 'curated',
  },
];
